name: Auto Sign In

on:
  schedule:
    - cron: '49 23 * * *'  # 每天 UTC 0点运行
  workflow_dispatch:      # 支持手动触发

jobs:
  sign-in:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
    
    - name: Create env file
      run: |
        echo "SIGNIN_USERNAME=${{ secrets.SIGNIN_USERNAME }}" > .env
        echo "SIGNIN_PASSWORD=${{ secrets.SIGNIN_PASSWORD }}" >> .env
        echo "SENDKEY=${{ secrets.SENDKEY }}" >> .env
    
    - name: Run sign-in script
      run: python auto_signin.py
    
    - name: Upload screenshots
      if: always()  # 即使脚本失败也上传截图
      uses: actions/upload-artifact@v4
      with:
        name: signin-screenshots
        path: screenshots/
        retention-days: 7  # 保存7天
